extends Node
## IT/EN localisation. Autoloaded as `Loc`, right after Settings.
##
## Two lookup styles:
##   Loc.t("menu.new")          -> key-based, for UI chrome we own
##   Loc.tx("BLOCKED by #4")    -> value-based, for gameplay callouts emitted
##                                 deep inside the sim (Court/AIBrain/Career).
##                                 Unknown strings pass through untouched, so
##                                 untranslated content degrades to English
##                                 instead of breaking.
## The language lives in Settings ("lang"), defaults to the device locale.

signal changed

var lang := "en"

# key -> [english, italian]
const STR := {
	"tagline":        ["Baskin: inclusive basketball. Play it, learn it.",
	                   "Baskin: il basket inclusivo. Giocalo, imparalo."],
	"menu.continue":  ["CONTINUE CAREER", "CONTINUA LA CARRIERA"],
	"menu.new":       ["NEW CAREER", "NUOVA CARRIERA"],
	"menu.quick":     ["QUICK EXHIBITION", "ESIBIZIONE RAPIDA"],
	"menu.settings":  ["SETTINGS", "IMPOSTAZIONI"],
	"menu.quit":      ["QUIT", "ESCI"],
	"menu.play":      ["PLAY", "GIOCA"],
	"menu.play.sub":  ["5v5 with the real baskin rules",
	                   "5v5 con le vere regole baskin"],
	"menu.how":       ["HOW TO PLAY", "COME SI GIOCA"],
	"menu.how.sub":   ["the court, the 5 roles, the points — 2 minutes", "il campo, i 5 ruoli, i punti — 2 minuti"],
	"setup.title":    ["INDOOR GAME", "PARTITA INDOOR"],
	"setup.sub":      ["Set the game up, then tip off.",
	                   "Imposta la partita, poi si scende in campo."],
	"setup.my_team":  ["YOUR TEAM  ·  %s", "LA TUA SQUADRA  ·  %s"],
	"setup.opponent": ["OPPONENT", "AVVERSARIO"],
	"setup.their_kit": ["OPPONENT KIT  ·  %s", "DIVISA AVVERSARIA  ·  %s"],
	"setup.format":   ["GAME TYPE", "TIPO DI PARTITA"],
	"setup.friendly": ["FRIENDLY  ·  no bench", "AMICHEVOLE  ·  senza panchina"],
	"setup.official": ["OFFICIAL  ·  bench & rotations", "UFFICIALE  ·  panchina e rotazioni"],
	"setup.friendly_short": ["friendly", "amichevole"],
	"setup.official_short": ["official", "ufficiale"],
	"setup.venue":    ["COURT", "CAMPO"],
	"setup.home":     ["HOME  ·  %s", "IN CASA  ·  %s"],
	"setup.away":     ["AWAY  ·  %s", "TRASFERTA  ·  %s"],
	"setup.tipoff":   ["TIP OFF", "PALLA A DUE"],
	"setup.summary":  ["%s vs %s  ·  4 periods of %s  ·  %s  ·  %s",
	                   "%s vs %s  ·  4 tempi da %s  ·  %s  ·  %s"],
	"setup.kit_locked": ["in use", "in uso"],
	"setup.home_short": ["HOME", "IN CASA"],
	"setup.away_short": ["AWAY", "TRASFERTA"],
	"setup.colour":   ["FLOOR", "PARQUET"],
	"setup.floor_maple": ["Maple", "Legno"],
	"setup.floor_blue":  ["Blue", "Blu"],
	"post.menu":      ["BACK TO MENU", "TORNA AL MENU"],
	"post.rematch":   ["PLAY ANOTHER GAME", "GIOCA UN'ALTRA PARTITA"],
	"exit.title":     ["Leave the game?", "Lasciare la partita?"],
	"exit.body":      ["You are walking out with the game unfinished. No rewards for this game.",
	                   "Stai uscendo a partita in corso. Questa partita non assegna ricompense."],
	"exit.confirm":   ["Quit to the menu", "Esci al menu"],
	"exit.keep":      ["Keep playing", "Continua a giocare"],
	"exit.toast":     ["You walked out on the game", "Hai lasciato la partita"],
	"intro.skip":     ["TAP TO SKIP", "TOCCA PER SALTARE"],
	"common.back":    ["BACK", "INDIETRO"],
	"settings.title": ["Settings", "Impostazioni"],
	"settings.display": ["DISPLAY", "SCHERMO"],
	"settings.controls": ["CONTROLS", "COMANDI"],
	"settings.audio": ["AUDIO", "AUDIO"],
	"settings.save":  ["SAVE", "SALVATAGGIO"],
	"settings.fps":   ["Target 60 FPS", "Target 60 FPS"],
	"settings.meter": ["Show shot meter", "Mostra indicatore di tiro"],
	"settings.left":  ["Left-handed buttons", "Pulsanti per mancini"],
	"settings.stick": ["Joystick sensitivity", "Sensibilità joystick"],
	"settings.sfx":   ["Sound effects", "Effetti sonori"],
	"settings.music": ["Music", "Musica"],
	"settings.lang":  ["Language", "Lingua"],
	"settings.del":   ["Delete career save", "Elimina il salvataggio"],
	"settings.deleted": ["Save deleted", "Salvataggio eliminato"],
	"status.day":     ["Day", "Giorno"],
	"match.shoot":    ["SHOOT", "TIRA"],
	"match.dunk":     ["DUNK", "SCHIACCIA"],
	"match.trick":    ["TRICK", "FINTA"],
	"match.pass":     ["PASS", "PASSA"],
	"match.pnr":      ["P&R", "BLOCCO"],
	"match.jump":     ["JUMP", "SALTA"],
	"match.steal":    ["STEAL", "RUBA"],
	"match.defend":   ["DEFEND", "DIFENDI"],
	"match.check":    ["CHECK", "CHECK"],
	"match.exit":     ["EXIT", "ESCI"],
	"match.timeout":  ["TIMEOUT", "TIMEOUT"],
	"match.bench.title": ["ON THE BENCH", "IN PANCHINA"],
	"match.bench.sub":   ["Earn your minutes back", "Guadagnati di nuovo i minuti"],
	"match.bench.watch": ["WATCH", "GUARDA"],
	"match.bench.sim":   ["SIM TO RETURN", "SIMULA FINO AL RIENTRO"],
	"callout.coach.tired": ["Coach: you are running on fumes -- rest!",
	                        "Coach: hai finito la benzina -- rifiata!"],
	"callout.coach.bench": ["Coach: to the bench! Make an impact out there",
	                        "Coach: in panchina! Serve più impatto"],
	"callout.coach.back":  ["Coach: you are back in -- make it count!",
	                        "Coach: si rientra -- falla contare!"],
	"match.len.title": ["PERIOD LENGTH", "DURATA TEMPI"],
	"callout.coach.rest": ["Coach: planned rest -- to the bench",
	                       "Coach: riposo programmato -- in panchina"],
	"callout.coach.goin": ["Coach: back in, go get them!",
	                       "Coach: si torna in campo, prendili!"],
	"callout.no.timeouts": ["No timeouts left!", "Timeout esauriti!"],
	"callout.timeouts.left": ["%d left", "ne restano %d"],
	"sweep.0": ["Nothing left to read in %s.", "Niente più da leggere in %s."],
	"sweep.1": ["Take it down", "Staccalo"],
	"sweep.2": ["Hang this one", "Appendi questo"],
	"sweep.3": ["Buy it", "Compralo"],
	"sweep.4": ["Not now", "Non ora"],
	"sweep.5": ["Read it (on your shelf)", "Leggilo (sulla tua mensola)"],
	"sweep.6": ["Buy for %d$", "Compra a %d$"],
	"sweep.7": ["Put it back", "Rimetti a posto"],
	"sweep.8": ["Turn the page  \u25b6", "Gira pagina  ▶"],
	"sweep.9": ["Put it down", "Appoggialo"],
	"sweep.10": ["Close", "Chiudi"],
	"sweep.11": ["Finish the chapter  (%d min)", "Finisci il capitolo  (%d min)"],
	"sweep.12": ["Stop here (no progress)", "Fermati qui (nessun progresso)"],
	"sweep.13": ["%s\\n%s", "%s\\n%s"],
	"sweep.14": ["PAGE & PRINT", "CARTA & STAMPA"],
	"sweep.15": ["Posters for the wall, books for the head.", "Poster per la parete, libri per la testa."],
	"sweep.16": ["\u2713 ", "✓ "],
	"sweep.17": ["\ud83d\udcd6  ", "📖  "],
	"sweep.18": ["Not enough money", "Soldi insufficienti"],
	"sweep.19": ["Already own %s", "Hai già %s"],
	"sweep.20": ["%s bought · placed in the second apartment", "%s comprato · piazzato nel secondo appartamento"],
	"sweep.21": ["Second floor: %s", "Secondo piano: %s"],
	"sweep.22": ["%d$", "%d$"],
	"sweep.23": ["HOME & HEARTH", "CASA & FOCOLARE"],
	"sweep.24": ["Furnish the second apartment. Buy a piece and it is placed there, ready to use.", "Arreda il secondo appartamento. Compri un pezzo e viene piazzato lì, pronto all'uso."],
	"sweep.25": ["bought", "comprato"],
	"sweep.26": ["not bought yet", "non ancora comprato"],
	"sweep.27": ["Adopt", "Adotta"],
	"sweep.28": ["< Leave", "< Esci"],
	"sweep.29": ["\ud83d\udc3e  Paws & Claws", "🐾  Zampe & Artigli"],
	"sweep.30": ["$%d", "$%d"],
	"sweep.31": ["$%d   ·   food x%d", "$%d   ·   cibo x%d"],
	"sweep.32": ["No pets yet. An empty flat is a quiet flat.", "Ancora nessun pet. Una casa vuota è una casa silenziosa."],
	"sweep.33": ["Owned", "Posseduto"],
	"sweep.34": ["Buy", "Compra"],
	"sweep.35": ["Too dear", "Troppo caro"],
	"sweep.36": ["Bought  %s", "Comprato  %s"],
	"sweep.37": ["Back", "Indietro"],
	"sweep.38": ["Plunge  ·  $%d", "Tuffo  ·  $%d"],
	"sweep.39": ["GO OUTSIDE", "ESCI FUORI"],
	"sweep.40": ["GEAR SHELF", "MENSOLA ATTREZZI"],
	"sweep.41": ["Home sweet home", "Casa dolce casa"],
	"sweep.42": ["Delivery arrived", "Consegna arrivata"],
	"sweep.43": ["Day %d · woke at %s", "Giorno %d · sveglio alle %s"],
	"sweep.44": ["Slept until %s", "Hai dormito fino alle %s"],
	"sweep.45": ["Rested on the extra bed", "Riposo sul letto extra"],
	"sweep.46": ["Showered upstairs", "Doccia al piano di sopra"],
	"sweep.47": ["Sat down", "Ti sei seduto"],
	"sweep.48": ["Watched TV upstairs", "TV guardata al piano di sopra"],
	"sweep.49": ["Quiet workspace", "Postazione tranquilla"],
	"sweep.50": ["Second apartment unlocked", "Secondo appartamento sbloccato"],
	"sweep.51": ["You need 1000$", "Ti servono 1000$"],
	"sweep.52": ["Wearing %s", "Indossi %s"],
	"sweep.53": ["TV off", "TV spenta"],
	"sweep.54": ["Chilled out for an hour", "Un'ora di relax"],
	"sweep.55": ["Correct", "Corretto"],
	"sweep.56": ["Missed it -- that one was fine", "Sbagliato -- quella era giusta"],
	"sweep.57": ["Shower. %s  (+12 energy)", "Doccia. %s  (+12 energia)"],
	"sweep.58": ["Order a delivery (+3 basics, 25$)", "Ordina una consegna (+3 basi, 25$)"],
	"sweep.59": ["EAT IT", "MANGIALO"],
	"sweep.60": ["\ud83d\udca4  Until 07:00 · %dh%02dm · +%d", "💤  Fino alle 07:00 · %dh%02dm · +%d"],
	"sweep.61": ["Get up", "Alzati"],
	"sweep.62": ["Lie down (+8 energy)", "Sdraiati (+8 energia)"],
	"sweep.63": ["Shower (+12 energy)", "Doccia (+12 energia)"],
	"sweep.64": ["Sit a while (+5 energy)", "Siediti un po' (+5 energia)"],
	"sweep.65": ["Watch (+6 energy)", "Guarda (+6 energia)"],
	"sweep.66": ["Sit at the desk", "Siediti alla scrivania"],
	"sweep.67": ["BUY APARTMENT  ·  1000$", "COMPRA APPARTAMENTO  ·  1000$"],
	"sweep.68": ["Watch for an hour (relax, +8 energy)", "Guarda per un'ora (relax, +8 energia)"],
	"sweep.69": ["Feed %s", "Dai da mangiare a %s"],
	"sweep.70": ["\ud83e\uddf9  Clean up %d mess(es)", "🧹  Pulisci %d pastrocchi"],
	"sweep.71": ["Start the shift  (2h, \u221220 energy)", "Inizia il turno  (2h, −20 energia)"],
	"sweep.72": ["Review attributes & badges", "Rivedi attributi e badge"],
	"sweep.73": ["\ud83d\udeaa  GO OUTSIDE", "🚪  ESCI FUORI"],
	"sweep.74": ["\ud83d\udcf1", "📱"],
	"sweep.75": ["\ud83d\udecf  Bed", "🛏  Letto"],
	"sweep.76": ["  %s", "  %s"],
	"sweep.77": ["\ud83e\ude9c  Second apartment", "🪜  Secondo appartamento"],
	"sweep.78": ["\ud83d\udcfa  Highlights", "📺  Sintesi"],
	"sweep.79": ["\ud83d\udc3e  Pets", "🐾  Pet"],
	"sweep.80": ["\ud83e\ude9f  Window", "🪟  Finestra"],
	"sweep.81": ["\ud83d\udcbb  Desk", "💻  Scrivania"],
	"sweep.82": ["\ud83d\udcbb  Job %d of 6", "💻  Turno %d di 6"],
	"sweep.83": ["\ud83d\udcbb  Shift over", "💻  Turno finito"],
	"sweep.84": ["WIN", "VITTORIA"],
	"sweep.85": ["The street is quiet.", "La strada è tranquilla."],
	"sweep.86": ["  (perfect-shift bonus)", "  (bonus turno perfetto)"],
	"sweep.87": ["DOWN", "GIÙ"],
	"sweep.88": ["LOSS", "SCONFITTA"],
	"sweep.89": ["STAIRS", "SCALE"],
	"sweep.90": ["ENTER", "ENTRA"],
	"sweep.91": ["Welcome to Iron Gym", "Benvenuto alla Iron Gym"],
	"sweep.92": ["Too tired. Eat or sleep first.", "Troppo stanco. Mangia o dormi prima."],
	"sweep.93": ["\ud83d\udcaa  START  (-%d energy)", "💪  VIA  (-%d energia)"],
	"sweep.94": ["weights", "pesi"],
	"sweep.95": ["cardio", "cardio"],
	"sweep.96": ["Too tired.", "Troppo stanco."],
	"sweep.97": ["Shift started!", "Turno iniziato!"],
	"sweep.98": ["Good load! %d/%d", "Bel carico! %d/%d"],
	"sweep.99": ["Dropped it. %d/%d", "Caduto. %d/%d"],
	"sweep.100": ["Shift done. Accuracy %d%% -> +%d$", "Turno finito. Precisione %d%% -> +%d$"],
	"sweep.101": ["LOADING DOCKS", "BANCHINA DI CARICO"],
	"sweep.102": ["Tap when the marker is in the green zone. 12 crates.", "Tocca quando il marker è nella zona verde. 12 casse."],
	"sweep.103": ["HOLD", "TIENI"],
	"sweep.104": ["SHOOT", "TIRA"],
	"sweep.105": ["QUIT", "ESCI"],
	"sweep.106": ["%s   %.1fs   reps %d   missed %d   combo x%d", "%s   %.1fs   rip %d   perse %d   combo x%d"],
	"sweep.107": ["%s   %.1fs   in the zone %d%%", "%s   %.1fs   in zona %d%%"],
	"sweep.108": ["%s   %.1fs   score %.0f/%.0f   combo x%d", "%s   %.1fs   punti %.0f/%.0f   combo x%d"],
	"sweep.109": ["WALK ONTO THE CIRCLE", "CAMMINA SUL CERCHIO"],
	"sweep.110": ["MISS", "ERRORE"],
	"sweep.111": ["CLIPPED THE CONE", "CONO TOCCATO"],
	"sweep.112": ["CLEAN x%d", "PULITO x%d"],
	"sweep.113": ["WRONG HAND", "MANO SBAGLIATA"],
	"sweep.114": ["WRONG SIDE", "LATO SBAGLIATO"],
	"sweep.115": ["CROSSOVER", "CROSSOVER"],
	"sweep.116": ["ON THE HIP", "SUL FIANCO"],
	"sweep.117": ["CONTESTED! x%d", "CONTESTATO! x%d"],
	"sweep.118": ["AIR SWIPE", "PRESA A VUOTO"],
	"sweep.119": ["GRADE %s", "GRADO %s"],
	"sweep.120": ["PUSH HARDER", "SPINGI DI PIÙ"],
	"sweep.121": ["three", "tre"],
	"sweep.122": ["PERFECT!", "PERFETTO!"],
	"sweep.123": ["BEATEN", "BATTUTO"],
	"sweep.124": ["DEEP REP!", "REP PROFONDA!"],
	"sweep.125": ["TOO HIGH - let it come down", "TROPPO ALTO - fallo scendere"],
	"sweep.126": ["LEFT", "SINISTRA"],
	"sweep.127": ["EASE OFF", "MOLLA"],
	"sweep.128": ["mid", "medio"],
	"sweep.129": ["SWISH", "SWISH"],
	"sweep.130": ["GOOD REP", "BUONA REP"],
	"sweep.131": ["FORM BREAK", "FORMA PERSA"],
	"sweep.132": ["RIGHT", "DESTRA"],
	"sweep.133": ["Too tired -- you need %d energy", "Troppo stanco -- ti servono %d energia"],
	"sweep.134": ["COURT WORK", "LAVORO IN CAMPO"],
	"sweep.135": ["TEAM COURT", "CAMPO DI SQUADRA"],
	"sweep.136": ["Practice with the squad or run a scrimmage.", "Allenati con la squadra o fai uno scrimmage."],
	"sweep.137": ["RIVERSIDE ARENA", "ARENA RIVERSIDE"],
	"sweep.138": ["Home of the Ravens.", "Casa dei Ravens."],
	"sweep.139": ["HOME", "CASA"],
	"sweep.140": ["no game scheduled", "nessuna partita in programma"],
	"sweep.141": ["rest", "riposo"],
	"sweep.142": ["AWAY", "TRASFERTA"],
	"sweep.143": ["NEED %d ENERGY (you have %d) · rest first", "SERVONO %d ENERGIA (ne hai %d) · riposati prima"],
	"sweep.144": ["s", "s"],
	"sweep.145": ["\u25b6  TIP OFF", "▶  PALLA A DUE"],
	"sweep.146": ["in use", "in uso"],
	"sweep.147": ["YOUR TEAM  ·  %s", "LA TUA SQUADRA  ·  %s"],
	"sweep.148": ["OPPONENT  ·  %s", "AVVERSARI  ·  %s"],
	"sweep.149": ["TEAM KITS", "DIVISE"],
	"sweep.150": ["Choose the colours before you tip off.", "Scegli i colori prima della palla a due."],
	"sweep.151": ["Bought %s -- now on your wall", "Comprato %s -- ora sulla tua parete"],
	"sweep.152": ["Wall updated", "Parete aggiornata"],
	"sweep.153": ["Bought %s", "Comprato %s"],
	"sweep.154": ["You do not own that book.", "Non possiedi quel libro."],
	"sweep.155": ["Stairs", "Scale"],
	"sweep.156": ["Window", "Finestra"],
	"sweep.157": ["Fridge", "Frigo"],
	"sweep.158": ["Bed", "Letto"],
	"sweep.159": ["Wardrobe", "Armadio"],
	"sweep.160": ["TV", "TV"],
	"sweep.161": ["Desk", "Scrivania"],
	"sweep.162": ["Shower", "Doccia"],
	"sweep.163": ["Pets", "Pet"],
	"sweep.164": ["empty frame", "cornice vuota"],
	"sweep.165": ["Leave", "Esci"],
	"sweep.166": ["Your shelf is empty", "La tua mensola è vuota"],
	"sweep.167": ["START SHIFT", "INIZIA TURNO"],
	"sweep.168": ["LOAD CRATE", "CARICA CASSA"],
	"sweep.169": ["SHOOT AROUND (solo)", "TIRO DA SOLO"],
	"sweep.170": ["TEAM PRACTICE (today)", "PRATICA DI SQUADRA (oggi)"],
	"sweep.171": ["\u25b6  TIP OFF vs %s", "\u25b6  PALLA A DUE vs %s"],
	"sweep.172": ["Today's game is finished", "La partita di oggi è finita"],
	"sweep.173": ["\ud83d\udcc5  Season schedule", "\ud83d\udcc5  Calendario stagione"],
	"sweep.174": ["Next game: day %d vs %s  (in %d day%s)", "Prossima partita: giorno %d vs %s  (tra %d giorn%s)"],
	"sweep.175": ["NO GAME TODAY", "NESSUNA PARTITA OGGI"],
	"sweep.176": ["Every fixture, result and rest day", "Ogni partita, risultati e giorni di riposo"],
	"common.phone": ["PHONE", "TELEFONO"],
	"sweep.177": ["Sofa", "Divano"],
	"sweep.178": ["Rug", "Tappeto"],
	"sweep.179": ["Armchair", "Poltrona"],
	"sweep.180": ["Floor lamp", "Piantana"],
	"sweep.181": ["Plant", "Pianta"],
	"sweep.182": ["Bookshelf", "Libreria"],
	"sweep.183": ["Dining table", "Tavolo da pranzo"],
	"sweep.184": ["EQUIPPED", "EQUIAGGIATO"],
	"sweep.185": ["OWNED", "POSSEDUTO"],
	"sweep.186": ["EQUIP", "EQUIAGGIA"],
	"sweep.187": ["REMOVE", "TOGLI"],
	"sweep.188": ["LEG: %s", "GAMBA: %s"],
	"sweep.189": ["ARM: %s", "BRACCIO: %s"],
	"sweep.190": ["DX", "DX"],
	"sweep.191": ["SX", "SX"],
	"sweep.192": ["Knee sleeve", "Ginocchiera"],
	"sweep.193": ["Ankle brace", "Cavigliera"],
	"sweep.194": ["Wrist wrap", "Fascia polso"],
	"sweep.195": ["Compression tights", "Calze compressive"],
	"sweep.196": ["Call it! (pass button)", "Chiamala! (tasto passa)"],
	"settings.voice": ["Voices", "Voci"],
	"settings.crowd": ["Crowd", "Folla"],
	"match.home":     ["HOME", "CASA"],
	"match.away":     ["AWAY", "OSPITI"],
	"match.shotclk":  ["shot %s", "tiri %s"],
	"post.win":       ["WIN", "VITTORIA"],
	"post.loss":      ["LOSS", "SCONFITTA"],
	"post.grade":     ["Grade: %s", "Voto: %s"],
	"post.city":      ["BACK TO THE CITY", "TORNA IN CITTÀ"],
	"post.phone":     ["OPEN PHONE (check the feed)", "APRI IL PHONE (guarda il feed)"],
	# ---- broadcast pass (v2.1.0): intro card, commentary, jumbo, post card
	"bc.tonight":     ["TONIGHT", "STASERA"],
	"bc.vs":          ["vs", "vs"],
	"bc.tap":         ["TAP TO START", "TOCCA PER INIZIARE"],
	"bc.final":       ["FINAL", "FINALE"],
	"bc.record":      ["%dW-%dL", "%dV-%dP"],
	"bc.quarters":    ["BY PERIOD", "PER TEMPO"],
	"bc.top":         ["Top scorers: %s %d pts · %s %d pts", "Migliori: %s %d pt · %s %d pt"],
	"bc.run":         ["%d straight points by %s (Q%d)", "%d punti di fila di %s (Q%d)"],
	"bc.scrimmage":   ["SCRIMMAGE", "ALLENAMENTO"],
	"bc.challenger":  ["STREET 1v1", "SFIDA 1v1"],
	"bc.style.run":   ["Run & Gun", "Run & Gun"],
	"bc.style.lock":  ["Lockdown D", "Difesa di ferro"],
	"bc.style.inside":["Inside-Out", "Dentro-Fuori"],
	"bc.style.grit":  ["Grit & Glass", "Grinta e rimbalzi"],
	"bc.style.none":  ["", ""],
	"comm.run":       ["%s are on a %d-point run!", "%s corre: %d punti di fila!"],
	"comm.dunk.0":    ["Oh! What a slam!", "Oh! Che schiacciata!"],
	"comm.dunk.1":    ["The rim is still shaking!", "Il ferro trema ancora!"],
	"comm.dunk.2":    ["Put that one on the wall!", "Quella va appesa al muro!"],
	"comm.three.0":   ["From downtown — bang!", "Dal centro — bang!"],
	"comm.three.1":   ["Nothing but net from deep!", "Solo reticello dal fondo!"],
	"comm.three.2":   ["He cannot miss tonight!", "Stasera non sbaglia una!"],
	"comm.cold.0":    ["The rim is closed tonight...", "Stasera il ferro è chiuso..."],
	"comm.cold.1":    ["Ice cold stretch — somebody heat the ball up!", "Ghiaccio puro — qualcuno scaldi la palla!"],
	"comm.lead.0":    ["The lead changes hands!", "Cambia il vantaggio!"],
	"comm.lead.1":    ["Swing! Nobody gives an inch here!", "Ribalta! Qui non si regala un centimetro!"],
	"comm.qend.0":    ["End of the period.", "Fine del tempo."],
	"comm.qend.1":    ["Ten to regroup, then back at it.", "Dieci per riprendersi, poi si riparte."],
	"comm.clutch":    ["Under thirty seconds — this is anyone's game!", "Meno di trenta secondi — la partita è in bilico!"],
	"jumbo.welcome":  ["WELCOME TO %s", "BENVENUTI AL %s"],
	"jumbo.slam":     ["SLAM!", "SCHIACCIA!"],
	"jumbo.three":    ["FROM DEEP!", "DAL FONDO!"],
	"jumbo.noise":    ["MAKE SOME NOISE!", "FATE DEL RUMORE!"],
	"jumbo.dance":    ["DANCE CAM!", "DANCE CAM!"],
	"jumbo.defense":  ["DE-FENSE!", "DIFE-NSA!"],
	"creator.title":  ["CREATE YOUR PLAYER", "CREA IL TUO GIOCATORE"],
	"creator.sub":    ["Height and weight really change acceleration and contact.",
	                   "Altezza e peso cambiano davvero accelerazione e contatti."],
	"creator.pos":    ["Position: %s", "Ruolo: %s"],
	"creator.height": ["Height  %d cm", "Altezza  %d cm"],
	"creator.weight": ["Weight  %d kg", "Peso  %d kg"],
	"creator.team":   ["Team: %s", "Squadra: %s"],
	"creator.jersey": ["Jersey  #%d", "Maglia  #%d"],
	"creator.skin":   ["Skin", "Carnagione"],
	"creator.hair":   ["Hair", "Capelli"],
	"creator.hand":   ["Hand", "Mano"],
	"phone.messages": ["Messages", "Messaggi"],
	"phone.social":   ["HoopFeed", "HoopFeed"],
	"phone.calendar": ["Calendar", "Calendario"],
	"phone.shop":     ["Store", "Negozio"],
	"phone.profile":  ["My Card", "La mia scheda"],
	"phone.stats":    ["Stats", "Statistiche"],
	"phone.wallpaper": ["Wallpaper", "Sfondo"],
	"w.clear":        ["Sunny", "Sereno"],
	"w.cloudy":       ["Cloudy", "Nuvoloso"],
	"w.rain":         ["Rain", "Pioggia"],
	"w.snow":         ["Snow", "Neve"],
	"s.winter":       ["Winter", "Inverno"],
	"s.spring":       ["Spring", "Primavera"],
	"s.summer":       ["Summer", "Estate"],
	"s.autumn":       ["Autumn", "Autunno"],
	"rule.tip":        ["TIP-OFF · ONLY ROLE 5 JUMPS", "PALLA A DUE · SALTANO SOLO I RUOLI 5"],
	"rule.tip.body":   ["Only role-5 players contest the opening jump ball. Everyone else clears the circle.",
	                   "Solo i ruoli 5 saltano per la palla a due iniziale. Gli altri lasciano il cerchio."],
	"rule.r1_make":    ["ROLE 1 · THE PIVOT SCORES", "RUOLO 1 · IL PIVOT SEGNA"],
	"rule.r1_make.body": ["The pivot shoots at the SIDE basket: the 1st attempt of a possession is worth 3 points, the 2nd worth 2.",
	                   "Il pivot tira al canestro LATERALE: il 1° tiro di un possesso vale 3 punti, il 2° ne vale 2."],
	"rule.r1_sub":     ["PIVOT CHANGE", "CAMBIO PIVOT"],
	"rule.r1_sub.body": ["3 made baskets in one period: the pivot MUST leave the floor. Another role 1 takes his place.",
	                   "3 canestri in un tempo: il pivot DEVE uscire. Un altro ruolo 1 entra al suo posto."],
	"rule.r2_make":    ["ROLE 2 SCORES", "RUOLO 2 SEGNA"],
	"rule.r2_make.body": ["Role 2 is a pivot: he takes the hand-off inside his area, steps back out and shoots at the side basket — worth 3.",
	                   "Ruolo 2: 2 punti dal centro, 3 dai lati — sempre da FUORI area, dopo 2 palleggi."],
	"rule.r3_make":    ["ROLE 3 SCORES", "RUOLO 3 SEGNA"],
	"rule.r3_make.body": ["Role 3: 2 points at the side baskets, 3 at the classic ones (2 if he received the ball inside the side area).",
	                   "Ruolo 3: 2 punti ai laterali, 3 ai classici (2 se ha ricevuto palla in area laterale)."],
	"rule.r4_make":    ["ROLE 4 SCORES", "RUOLO 4 SEGNA"],
	"rule.r4_make.body": ["Role 4 shoots ONLY at the classic baskets — 2 inside the arc, 3 beyond it — always after a full stop.",
	                   "Il ruolo 4 tira SOLO ai canestri classici — 2 dentro l'arco, 3 fuori — sempre dopo un arresto completo."],
	"rule.r5_make":    ["ROLE 5 SCORES", "RUOLO 5 SEGNA"],
	"rule.r5_make.body": ["Role 5 plays the classic game: 2 inside the arc, 3 beyond. But: max 3 shots per period.",
	                   "Il ruolo 5 gioca classico: 2 dentro l'arco, 3 fuori. Ma: max 3 tiri per tempo."],
	"rule.v_dribble2": ["VIOLATION · DRIBBLE FIRST (ROLE 2)", "INFRAZIONE · PRIMA PALLEGGIA (RUOLO 2)"],
	"rule.v_dribble2.body": ["Role 2 must take at least 2 dribbles before shooting. Turnover.",
	                   "Il ruolo 2 deve fare almeno 2 palleggi prima di tirare. Palla agli avversari."],
	"rule.v_dribble3": ["VIOLATION · DRIBBLE FIRST (ROLE 3)", "INFRAZIONE · PRIMA PALLEGGIA (RUOLO 3)"],
	"rule.v_dribble3.body": ["Role 3 must dribble at least twice on the run before shooting. Turnover.",
	                   "Il ruolo 3 deve palleggiare almeno 2 volte in corsa prima di tirare. Palla agli avversari."],
	"rule.v_layup3":   ["VIOLATION · NO LAYUP (ROLE 3)", "INFRAZIONE · NIENTE TERZO TEMPO (RUOLO 3)"],
	"rule.v_layup3.body": ["Role 3 may never shoot on the run near the basket: no layups. Stop or pull up. Turnover.",
	                   "Il ruolo 3 non può tirare in corsa vicino a canestro: niente terzo tempo. Arrestati. Palla agli avversari."],
	"rule.v_stop4":    ["VIOLATION · STOP FIRST (ROLE 4)", "INFRAZIONE · PRIMA L'ARRESTO (RUOLO 4)"],
	"rule.v_stop4.body": ["Role 4 must come to a complete stop before shooting. Turnover.",
	                   "Il ruolo 4 deve fermarsi completamente prima di tirare. Palla agli avversari."],
	"rule.sub":        ["SUBSTITUTION", "SOSTITUZIONE"],
	"rule.sub.body":   ["A substitution is legal at any dead ball on request. The reserve comes in with the SAME ROLE as the man going out (the line-up must stay legal: two women on the floor, one pivot).",
		"La sostituzione e' legale a ogni palla morta, su richiesta. Chi entra prende lo STESSO RUOLO di chi esce (la formazione deve restare regolare: due donne in campo, un solo pivot)."],
	"rule.v_dbl":      ["VIOLATION · DOUBLE DRIBBLE", "INFRAZIONE · DOPPIO PALLEGGIO"],
	"rule.v_dbl.body": ["The fake GATHERS the ball (held in both hands): from that moment you may only pass or shoot. Dribbling again is a double dribble — the ball goes to the opponents.",
		"La finta RACCOGLIE la palla (ferma nelle mani): da li' in poi puoi solo passare o tirare. Se la rimetti a terra e palleggi e' doppio palleggio — palla agli avversari."],
	"rule.v_area":     ["VIOLATION · OUTSIDE THE AREA", "INFRAZIONE · FUORI DALL'AREA"],
	"rule.v_area.body": ["Shots at the side baskets must be taken from OUTSIDE the painted area. Turnover.",
	                   "I tiri ai canestri laterali vanno presi da FUORI dall'area disegnata. Palla agli avversari."],
	"rule.v_lim5":     ["VIOLATION · SHOT LIMIT (ROLE 5)", "INFRAZIONE · LIMITE TIRI (RUOLO 5)"],
	"rule.v_lim5.body": ["Role 5 may take at most 3 shots per period. Turnover.",
	                   "Il ruolo 5 può tirare al massimo 3 volte per tempo. Palla agli avversari."],
	"rule.v_lim3":     ["VIOLATION · MAX 3 MAKES", "INFRAZIONE · MAX 3 CANESTRI"],
	"rule.v_lim3.body": ["Roles 1–4 may make at most 3 baskets per period. Turnover.",
	                   "I ruoli 1–4 possono segnare al massimo 3 canestri per tempo. Palla agli avversari."],
	"rule.v_pivot5s":  ["VIOLATION · PIVOT CLOCK", "INFRAZIONE · TEMPO DEL PIVOT"],
	"rule.v_pivot5s.body": ["The pivot (roles 1–2) must shoot within 10 seconds of the hand-off — 7 for a 2R. Turnover.",
	                   "Il pivot (ruoli 1–2) deve tirare entro 5 secondi — 10 con carrozzina o tutor. Palla agli avversari."],
	"rule.v_illegal":  ["FOUL L · ILLEGAL DEFENCE", "FALLO L · DIFESA IRREGOLARE"],
	"toast.foul_l": ["FOUL L · ILLEGAL DEFENCE #%d", "FALLO L di #%d · DIFESA IRREGOLARE"],
	"match.inbound.transition": ["THROW-IN", "RIMESSA"],
	"rule.v_illegal.body": ["ON DEFENCE ONLY: you may only guard a man of the SAME role or HIGHER (a role 5 only takes a 5); the role-2 pivot is taken by an opposing role 3, the role-1 pivot is never guarded. Standing still with room is legal. Counted as an \"L\" foul: 2 free throws + possession. A fouled role 3 shoots them at the high side basket, from the dashed line.",
	                   "SOLO IN DIFESA si marca un ruolo PARI o SUPERIORE (il ruolo 5 prende solo il 5); il pivot ruolo 2 lo prende un ruolo 3 avversario, il pivot ruolo 1 non è mai marcato. Stare fermi con spazio è lecito. È fallo \"L\": 2 tiri liberi + possesso. Se a subirlo è un ruolo 3, i tiri si battono al canestro laterale alto dalla linea tratteggiata."],
	"rule.tutor":      ["THE TUTOR", "IL TUTOR"],
	"rule.tutor.body": ["The 2T shooter plays with a TUTOR: a team-mate who positions him and gathers his miss.",
	                   "Il tiratore 2T gioca con un TUTOR: un compagno che lo posiziona e raccoglie il suo errore."],
	"t.tutor":         ["Tutor gathers the miss!", "Il tutor raccoglie l'errore!"],
	"t.change_ends":   ["CHANGE ENDS", "CAMBIO CAMPO"],
	"settings.difficulty": ["DIFFICULTY", "DIFFICOLTÀ"],
	"settings.diff0":  ["Easy", "Facile"],
	"settings.diff1":  ["Normal", "Normale"],
	"settings.diff2":  ["Hard", "Forte"],
	"settings.diff.hint": ["Easy: sleepy opponents. Hard: they close out, double up and punish you.",
	                       "Facile: avversari distratti. Forte: chiudono, raddoppiano e ti puniscono."],
	"rule.v_3sec":     ["3 SECONDS · you may not camp in the key", "3 SECONDI · non si sosta nell'area"],
	"t.foul.inbound":  ["FOUL · throw-in", "FALLO · rimessa"],
	"t.foul.bonus":    ["FOUL · bonus: 2 free throws", "FALLO · bonus: 2 tiri liberi"],
	"t.foul.charge":   ["OFFENSIVE FOUL · the ball goes the other way", "FALLO IN ATTACCO · palla agli avversari"],
	"pop.rebound":     ["REBOUND!", "RIMBALZO!"],
	"t.rebound":       ["Rebound #%d", "Rimbalzo #%d"],
	"t.sub.req":       ["Sub: #%d off, #%d on — at the next dead ball",
		"Cambio: fuori #%d, dentro #%d — alla prossima palla morta"],
	"t.sub.done":      ["SUB: #%d in for #%d", "CAMBIO: entra #%d per #%d"],
	"t.sub.self":      ["Sub for YOU: the coach will call you back",
		"Cambio per te: l'allenatore ti richiama in campo"],
	"t.sub.none":      ["Nobody to sub right now", "Nessun cambio disponibile adesso"],
	"match.sub":           ["SUBS", "CAMBIO"],
	"match.sub.title":     ["SUBSTITUTIONS", "SOSTITUZIONI"],
	"match.sub.hint":      ["Pick who comes OFF on the left, then who goes IN on the right. The swap happens at the next dead ball.",
		"Scegli chi ESCE a sinistra, poi chi ENTRA a destra. Il cambio avviene alla prima palla morta."],
	"match.sub.hint2":     ["#%d selected: now pick who goes in", "#%d scelto: ora scegli chi entra"],
	"match.sub.pick":      ["First pick who comes off (left)", "Prima scegli chi esce (a sinistra)"],
	"match.sub.oncourt":   ["ON COURT", "IN CAMPO"],
	"match.sub.bench":     ["BENCH", "PANCHINA"],
	"match.sub.close":     ["CLOSE", "CHIUDI"],
	"t.ftlive":        ["LAST FREE THROW MISSED · LIVE BALL", "ULTIMO LIBERO SBAGLIATO · PALLA VIVA"],
	"t.bonus.team":    ["%s reached 5 team fouls · from now on free throws", "%s arrivata a 5 falli di squadra · da ora si tira dalla lunetta"],
	"t.handoff":       ["Hand-off!", "Consegna!"],
	"t.timeout.breather": ["TIMEOUT · legs back", "TIMEOUT · gambe recuperate"],
	"rule.v_5sec":     ["5 SECONDS · closely guarded", "5 SECONDI · marcato stretto"],
	"t.three_sec_warn": ["3 sec!", "3 secondi!"],
	"t.five_sec_warn":  ["5 sec -- move it!", "5 secondi -- falla girare!"],
	"match.endperiod": ["END OF PERIOD %d", "FINE TEMPO %d"],
	"hud.shots":       ["shots", "tiri"],
	"hud.makes":       ["makes", "canestri"],
	"role.pick":       ["CHOOSE YOUR ROLE", "SCEGLI IL TUO RUOLO"],
	"role.1":          ["ROLE 1 · PIVOT", "RUOLO 1 · PIVOT"],
	"role.1.d":        ["PIVOT in a wheelchair, never guarded. Ball handed to you INSIDE the area at the LOW side basket (1.20 m). First shot 3 pts, second 2. 10s to shoot.",
	                   "PIVOT in carrozzina, mai marcato. Palla consegnata DENTRO l'area al canestro laterale BASSO (1,20 m). Primo tiro 3 pt, secondo 2. 10s per tirare."],
	"role.1.hint":     ["Get the hand-off INSIDE your area — then stop and shoot within 10s!", "Ricevi la consegna DENTRO l'area — poi fermati e tira entro 10s!"],
	"role.2":          ["ROLE 2 · PIVOT", "RUOLO 2 · PIVOT"],
	"role.2.d":        ["Second pivot: receives by hand INSIDE the area, 2 dribbles, then steps out and shoots at the HIGH side basket (2.20 m): central sector 2 pts, lateral 3. 10s (7 if 2R).",
	                   "Secondo pivot: riceve a mano DENTRO l'area, 2 palleggi, poi esce e tira nel laterale ALTO (2,20 m): settore centrale 2 pt, laterale 3. 10s (7 se 2R)."],
	"role.2.hint":     ["Hand-off inside, 2 dribbles, step out: a LATERAL sector is worth 3!", "Consegna dentro, 2 palleggi, esci: dal SETTORE LATERALE vale 3!"],
	"role.3":          ["ROLE 3", "RUOLO 3"],
	"role.3.d":        ["2 running dribbles. No layups. Side 2, classic 3.",
	                   "2 palleggi in corsa. Niente terzo tempo. Laterale 2, classico 3."],
	"role.3.hint":     ["No layups: stop or pull up before you shoot!", "Niente terzo tempo: arrestati prima di tirare!"],
	"role.4":          ["ROLE 4", "RUOLO 4"],
	"role.4.d":        ["Classic baskets only. Full stop before every shot.",
	                   "Solo canestri classici. Arresto completo prima di tirare."],
	"role.4.hint":     ["Classic baskets only — stop fully before shooting!", "Solo canestri classici — fermati prima di tirare!"],
	"role.5":          ["ROLE 5", "RUOLO 5"],
	"role.5.d":        ["Classic game. Jumps the tip. Max 3 shots per period.",
	                   "Gioco classico. Salta la palla a due. Max 3 tiri per tempo."],
	"role.5.hint":     ["Your game — but only 3 shots per period!", "Il tuo gioco — ma solo 3 tiri per tempo!"],

	"rolepick.title":  ["CHOOSE YOUR ROLE", "SCEGLI IL TUO RUOLO"],
	"guide.title":     ["HOW TO PLAY", "COME SI GIOCA"],
	"guide.sub":       ["Baskin: everyone on one court, each with his own game.", "Baskin: tutti sullo stesso campo, ognuno con la sua partita."],
	"guide.what_h":    ["WHAT IS BASKIN?", "COS'È IL BASKIN?"],
	"guide.what":      ["Inclusive basketball: one ball, two teams of 6, five roles. Roles 1 and 2 (the pivots) shoot at the side baskets and are never guarded; roles 3, 4 and 5 play the classic game, each with its own limits. The lower role always guards the higher one (a 5 only guards a 5). Sum of the role numbers on the floor: max 23.",
	                   "Basket inclusivo: una palla, due squadre da 6, cinque ruoli. I ruoli 1 e 2 (i pivot) tirano nei canestri laterali e non sono mai marcati; i ruoli 3, 4 e 5 giocano la partita classica, ciascuno con i suoi limiti. Il ruolo più basso marca sempre il più alto (il 5 solo il 5). Somma dei numeri ruolo in campo: max 23."],
	"guide.court_h":   ["THE COURT", "IL CAMPO"],
	"guide.court":     ["A regular court plus TWO side baskets at half court, one per sideline, each with a HIGH hoop (2.20 m) and a LOW hoop (1.20 m) on the same pole. A 3 m semicircle around each pole is split into FIVE sectors: the central one (in front of the hoop) pays 2, the laterals pay 3. The dashed arc 0.7 m further out (3.70 m) is the line the 2R variant and the role-3 free throws shoot from.",
	                   "Un campo regolare più DUE canestri laterali a metà campo, uno per lato, ciascuno con ferro ALTO (2,20 m) e ferro BASSO (1,20 m) sullo stesso palo. Attorno a ogni palo un semicerchio di 3 m diviso in CINQUE settori: quello centrale (davanti al canestro) vale 2, i laterali 3. L'arco tratteggiato 0,7 m più fuori (3,70 m) è la linea da cui tirano la variante 2R e i tiri liberi del ruolo 3."],
	"guide.roles_h":   ["THE FIVE ROLES", "I CINQUE RUOLI"],
	"guide.points_h":  ["POINTS", "I PUNTI"],
	"guide.points":    ["Role 1: first shot 3, second 2 · Role 2: central sector 2, lateral sector 3 · Role 3: side basket 2, classic 3 (3 if caught outside the side area) · Roles 4-5: classic 2 or 3 by the arc · Free throws: 1.",
	                   "Ruolo 1: primo tiro 3, secondo 2 · Ruolo 2: settore centrale 2, laterale 3 · Ruolo 3: laterale 2, classico 3 (3 se riceve fuori dall'area laterale) · Ruoli 4-5: classico 2 o 3 oltre l'arco · Tiri liberi: 1."],
	"guide.keys_h":    ["KEY RULES", "REGOLE CHIAVE"],
	"guide.keys":      ["Pivot (role 1-2): 10s to shoot from the hand-off (7s for 2R) · Role 2 must dribble twice before shooting · Roles 3-4-5 never ENTER the side areas, only to hand the ball over · Max 3 baskets per period for roles 1-4, max 3 shots for role 5 · Fouls: the bonus starts at the 5th team foul · 4 periods of 8 minutes.",
	                   "Pivot (ruoli 1-2): 10s per tirare dalla consegna (7s per il 2R) · Il ruolo 2 deve palleggiare due volte prima di tirare · I ruoli 3-4-5 non ENTRANO mai nelle aree laterali, solo per consegnare la palla · Max 3 canestri per tempo per i ruoli 1-4, max 3 tiri per il ruolo 5 · Falli: bonus dal 5° fallo di squadra · 4 tempi da 8 minuti."],
	"guide.controls_h": ["CONTROLS", "COMANDI"],
	"guide.controls":  ["Left half of the screen: virtual joystick to move · SHOOT: hold to charge, release in the golden window · PASS: pass to the aimed team-mate · TRICK: fake · In defence: STEAL / BLOCK. The REGOLE button (top right) reopens this quick reference during the match.",
	                   "Metà sinistra dello schermo: joystick per muoverti · TIRA: tieni premuto e rilascia nella finestra dorata · PASSA: passa al compagno mirato · FINTA: finta · In difesa: RUBA / BLOCCA. Il pulsante REGOLE (in alto a destra) riapre questo riepilogo durante la partita."],
	"guide.diagram":   ["Side area up close: 5 sectors, central pays 2, laterals pay 3.", "L'area laterale da vicino: 5 settori, il centrale vale 2, i laterali 3."],
	"rolepick.sub":    ["Five roles, one team: each plays a different game.", "Cinque ruoli, una squadra: ognuno gioca una partita diversa."],
	"rolepick.go":     ["TIP OFF", "PALLA A DUE"],
	"rolepick.as":     ["YOU PLAY AS %s", "GIOCHI COME %s"],
	"rules.btn":       ["RULES", "REGOLE"],
	"rules.title":     ["BASKIN RULES", "REGOLE BASKIN"],
	"rules.court_h":   ["THE COURT", "IL CAMPO"],
	"rules.court":     ["Two side baskets on the SAME pole at half court: HIGH 2.20 m (roles 2 and 3) and LOW 1.20 m (role 1). Around each one a 3 m semicircle split into 5 sectors; the DASHED arc at 3.70 m is where the 2R and the role-3 free throws shoot from. The numbers painted on the floor are what each spot pays.",
	                   "Due canestri laterali sullo STESSO palo a metà campo: ALTO 2,20 m (ruoli 2 e 3) e BASSO 1,20 m (ruolo 1). Attorno a ciascuno un semicerchio da 3 m diviso in 5 settori; l'arco TRATTEGGIATO a 3,70 m è la linea da cui tirano il 2R e i liberi del ruolo 3. I numeri dipinti a pavimento dicono quanto vale ogni posto."],
	"rules.score_h":   ["SCORING", "PUNTEGGI"],
	"rules.score":     ["Side baskets: R1 first shot 3 then 2 · R2 central sector 2, lateral sector 3 · R3 (from outside the line) 2. Classic baskets: R3 3 if caught outside the area, else 2 · R4/R5 2 inside, 3 behind the arc. Free throws 1 pt.",
	                   "Laterali: R1 primo tiro 3 poi 2 · R2 settore centrale 2, laterale 3 · R3 (da fuori linea) 2. Classici: R3 3 se riceve fuori area, altrimenti 2 · R4/R5 2 dentro, 3 oltre l'arco. Liberi 1 pt."],
	"rules.firsthint": ["First time? RULES (top right) explains everything.", "Prima volta? REGOLE (in alto a destra) spiega tutto."],
	"rules.viol_h":    ["WHISTLES", "FISCHI"],
	"rules.viol":      ["One pivot per team (role 1 or 2): he lives in his side area and only takes the ball from a hand INSIDE the area · Rebound after the pivot's shot: 2 per team, from OUTSIDE the semicircle (the pivot may step in) · Off his own miss the pivot must pass out · R3-R5 enter the side area only to deliver, then leave · Never guard a pivot · Max 3 makes (R1-R4), max 3 shots (R5)",
	                   "R2/R3: prima 2 palleggi · R3: niente terzo tempo · R4: arresto completo · Tiri laterali da FUORI area · Max 3 canestri (R1–R4), max 3 tiri (R5) · Il ruolo INFERIORE marca il superiore, mai il contrario (il 5 solo il 5): altrimenti fallo L, 2 liberi — SOLO IN DIFESA · Mai il pivot · Nessuno entra nell'area laterale avversaria · Palla al pivot solo da DENTRO la sua area."],
	"rules.hint":      ["Tap RULES anytime to close this card.", "Tocca REGOLE quando vuoi per chiudere."],
	"pop.central":     ["CENTRAL SECTOR", "SETTORE CENTRALE"],
	"pop.lateral":     ["LATERAL SECTOR", "SETTORE LATERALE"],
	"chip.r1a":        ["1ST SHOT · WORTH 3", "1° TIRO · VALE 3"],
	"chip.r1b":        ["2ND SHOT · WORTH 2", "2° TIRO · VALE 2"],
	"chip.r2out":      ["STEP OUT BEHIND YOUR LINE TO SHOOT", "ESCI DIETRO LA TUA LINEA PER TIRARE"],
	"chip.r2c":        ["CENTRAL SECTOR · 2 POINTS", "SETTORE CENTRALE · 2 PUNTI"],
	"chip.r2l":        ["LATERAL SECTOR · 3 POINTS", "SETTORE LATERALE · 3 PUNTI"],
	"chip.r3":         ["SIDE BASKET · 2 POINTS FROM OUTSIDE THE LINE", "CANESTRO LATERALE · 2 PUNTI DA FUORI LINEA"],

	"rule.foul":         ["DEFENSIVE FOUL", "FALLO DIFENSIVO"],
	"match.deliver.need_area": ["Pivot only gets the ball from INSIDE the area — carry it in and hand it over.", "Al pivot si consegna la palla solo da DENTRO l'area."],
	"match.deliver.two_man":   ["Move the ball to another team-mate first — no instant give-back to the pivot.", "Prima passa a un altro compagno: non si ripassa subito al pivot."],
	"match.area.reach":        ["That ball is the pivot's: roles 3-5 may not reach inside the area.", "Quella palla e' del pivot: i ruoli 3-5 non entrano nell'area."],
	"match.area.loose":        ["Ball in the area: it belongs to the pivot.", "Palla in area: e' del pivot."],
	"match.area.loose2":       ["Ball stuck in the area with a role-2 pivot: jump ball at centre court.", "Palla ferma in area con un pivot ruolo 2: palla a due a centro campo."],
	"rule.v_area_in":          ["VIOLATION · SMALL SIDE AREA", "INFRAZIONE · AREA LATERALE"],
	"rule.v_area_in.body":     ["Roles 3-5 may enter a small side area only to hand the ball to a pivot, then leave at once. Turnover.", "I ruoli 3-5 entrano nell'area laterale solo per consegnare la palla al pivot, poi escono subito. Palla agli avversari."],
	"rule.v_reb2":             ["VIOLATION · OWN REBOUND", "INFRAZIONE · RIMBALZO PROPRIO"],
	"rule.v_reb2.body":        ["Off your own missed shot you may NOT shoot again: pass the ball out to a rebounder. Turnover.", "Sul tuo rimbalzo non puoi ritirare: passa fuori a un rimbalzista. Palla agli avversari."],

	"rule.foul.body":    ["A defender in the shooter's landing space: the shooter takes 2 free throws (3 on a three-point attempt). Team fouls reset every quarter.",
	                       "Difensore addosso al tiratore: 2 tiri liberi (3 su tiro da tre). I falli di squadra si azzerano ogni quarto."],
	"match.foul.toast":  ["Foul on #%d", "Fallo di #%d"],
	"match.fouls":       ["FOULS %d-%d", "FALLI %d-%d"],
	"setup.next":        ["Next: choose your role", "Poi: scegli il tuo ruolo"],

	"rule.v_deliver":     ["BAD DELIVERY", "CONSEGNA SBAGLIATA"],
	"rule.v_deliver.body": ["The pivot's ball must be carried INTO the side area and handed over — never thrown from afar. Turnover.",
	                       "La palla del pivot va portata DENTRO l'area laterale e consegnata — mai passata da lontano. Palla persa."],

	"hud.pivotclk":      ["PIVOT %ds", "PIVOT %ds"],
	"hud.bonus":         ["BONUS %s", "BONUS %s"],

}

# English callout -> Italian, for strings emitted by the sim. Placeholders
# (%d / %s) are matched as wildcards so "BLOCKED by #34" still translates.
const CALLOUTS := {
	"PERFECT": "PERFETTO", "GOOD": "BELLO", "EARLY": "PRESTO", "LATE": "TARDI",
	"BLOCKED!": "STOPPATO!", "BLOCKED AT THE RIM!": "STOPPATA AL FERRO!",
	"BLOCKED by #%d": "STOPPATO da #%d", "STEAL!": "RUBATA!",
	"ANKLES!": "CAVIGLIE!", "DUNK!": "SLAM!", "BALL!": "PALLA!",
	"CHECK THE BALL": "CHECK", "CHECK THE BALL  %d - %d": "CHECK  %d - %d",
	"GO!": "VIA!", "Q1 - Tip-off": "Q1 - Palla a due",
	"Loose ball!": "Palla vagante!", "Loose ball recovered": "Palla vagante recuperata",
	"Covered — no lane": "Coperto — nessun varco", "No lane!": "Nessun varco!",
	"SCREEN": "BLOCCO", "ROLL": "ROLL", "Cleared - go!": "Libero - vai!",
	"Shot clock violation": "Violazione di 24\"", "Inbound": "Rimessa",
	"Intercepted!": "Intercettato!", "Turnover": "Palla persa",
	"Foul on #%d": "Fallo di #%d", "Free throws ×%d": "Tiri liberi ×%d",
	"Free throw made": "Libero a segno", "Free throw miss": "Libero sbagliato",
	"Rebound #%d": "Rimbalzo #%d", "Defender bit the fake!": "Il difensore ha abboccato!",
	"ON FIRE!": "IN FIAMME!", "UNSTOPPABLE!": "IMMARCABILE!",
	"Streak over": "Serie finita",
	"END Q%d": "FINE Q%d",
	"No shot from behind the hoop": "Non si tira da dietro il canestro",
	"PUMP FAKE": "FINTA DI TIRO",
	"DEFENSE ON — stay in front of your man": "DIFESA — resta davanti al tuo uomo",
	"Hold SHOOT to score - tap SHOOT to PUMP FAKE - TRICK shakes your man":
		"Tieni TIRA per segnare - tocca TIRA per la finta - FINTA sbilancia il difensore",
	"You walked out on the game": "Hai abbandonato la partita",
	"WINDMILL": "WINDMILL", "360": "360", "TOMAHAWK": "TOMAHAWK",
	"CRADLE": "CRADLE", "REVERSE": "REVERSE", "TWO-HAND": "DUE MANI",
	"SLAM": "SLAM",
	"MISS": "SBAGLIATO", "BANK": "TABELLONE", "VERY": "TROPPO",
}

var _rev := {}          # exact EN -> IT
var _patterns := []     # [Regex, IT template] for placeholder strings

func _init() -> void:
	for k in STR:
		_rev[STR[k][0]] = STR[k][1]
	for k in CALLOUTS:
		var en: String = k
		if en.contains("%"):
			var rx := RegEx.new()
			var pat := ""
			var i := 0
			while i < en.length():
				if en[i] == "%" and i + 1 < en.length():
					pat += "([-\\d\\w:#×\"]+)" if en[i + 1] == "s" else "([-\\d×\"]+)"
					i += 2
				else:
					pat += "\\" + en[i] if en[i] in "\\.^$|?*+()[]{}" else en[i]
					i += 1
			rx.compile("^" + pat + "$")
			_patterns.append([rx, CALLOUTS[en]])
		else:
			_rev[en] = CALLOUTS[en]

func _ready() -> void:
	lang = String(Settings.get_v("lang", _detect()))
	if lang != "it":
		lang = "en"

func _detect() -> String:
	var l := OS.get_locale()
	return "it" if l.begins_with("it") else "en"

func set_lang(l: String) -> void:
	lang = "it" if l == "it" else "en"
	Settings.set_v("lang", lang)
	changed.emit()

func toggle() -> void:
	set_lang("it" if lang == "en" else "en")

func t(key: String, fallback := "") -> String:
	var e = STR.get(key)
	if e == null:
		return fallback if fallback != "" else key
	var s: String = e[0] if lang == "en" else e[1]
	return s

## Translate a finished English string (callouts, toasts). Passthrough when
## unknown, so partially-localised content never shows garbage.
func tx(en_text: String) -> String:
	if lang == "en":
		return en_text
	if _rev.has(en_text):
		return String(_rev[en_text])
	for p in _patterns:
		var m: RegExMatch = p[0].search(en_text)
		if m:
			var out: String = p[1]
			var gi := 0
			var result := ""
			var pi := 0
			while pi < out.length():
				if out[pi] == "%" and pi + 1 < out.length():
					if gi < m.get_group_count():
						result += m.get_string(gi + 1)
					gi += 1
					pi += 2
				else:
					result += out[pi]
					pi += 1
			return result
	# Last resort: translate token by token so composite callouts such as
	# "GOOD / BANK +2" still read naturally instead of passing through raw.
	var parts := en_text.split(" ")
	var hit := false
	for i in parts.size():
		if _rev.has(parts[i]):
			parts[i] = String(_rev[parts[i]])
			hit = true
	return " ".join(parts) if hit else en_text